### PR TITLE
Task/walrus to orca

### PR DESCRIPTION
**Pull request by ahuoguo**
#42

### CODE REVIEW

**Comment by ejrgilbert** [comment]
Note, tests do pass, but there are still bugs when you look at the emitted code. Need to check on the following:
- [ ] Are Strings emitting properly? (offset seems wrong)
- [ ] Are predicates emitting properly? (true/false/partial)
- [ ] Are args saved/loaded properly?
- [ ] Are probe bodies emitted properly (within reason, dfinity use-case won't work because of not being able to lookup function names)
- [ ] Is `ic0:call_new` import call matched correctly?

**Comment by ahuoguo** [comment]
#81 is solved!

**Comment by ejrgilbert** [comment]
> #81 is solved! TO FIX: local id seems to be off Consider
> 
> ```c
> wasm:opcode:call:before {
>     i32 i;
>     i = 10;
> }
> ```
> 
> Running
> 
> ```
> wat2wasm tests/apps/handwritten/add.wat --debug-names -o tests/apps/handwritten/add.wasm && cargo run -- instr --script tests/scripts/instr.mm --app tests/apps/handwritten/add.wasm && wasm2wat --no-check output/output.wasm
> ```
> 
> gives me
> 
> ```webassembly
>   (func (;1;) (type 0)
>     (local i32 i32 i32)
>     i32.const 10
>     local.set 0
>     call 0
>     i32.const 10
>     local.set 1
>     call 0
>     i32.const 10
>     local.set 2
>     call 0)
> ```
> 
> However, they should be referring to the same local

Actually, this is expected behavior. A new local will be created for each place we inject that code.

**Comment by ejrgilbert** [comment]
From visual inspection, Strings are working now! I think we're good to go on merging this in.

**Pull request merged**
