### PR TITLE
[WIP] Moving the emitter from `walrus` to `wasmparser` and `wasm-encoder`

### PR DESCRIPTION
**Pull request by thesuhas**
#42 

- [x] round trip with orca (with some bugs in `spin`)

- Have basic support for instrumentation (`add.wat` example)
  - [x] emit_global
  - [ ] emit_assign_stmt
  
- Support `fold_expr`
  - [ ] be able to get `func_info` from call index

### CODE REVIEW

**Comment by ahuoguo** [comment]
The CI doesn't work now due to a bug when not hitting any event. See details in #76

**Comment by ejrgilbert** [comment]
Hi! Only did a quick glance. Please make a new emitter instead of editing the walrus one for now. It's easy to swap out the used emitter in main.rs. It just has to implement the Emitter trait in order to do the easy swap.

**Comment by ahuoguo** [comment]
I'm editing the entire file directly since the walrus rewriting emitter is huge. This PR is now still just trying to see how we can replicate walrus' behavior from orca.

**Comment by ejrgilbert** [comment]
Alrighty, sounds good :)

**Comment by ejrgilbert** [comment]
"Use orca visitor to detect instr_of_insterest (replace the InstrIter struct before)"

You won't need to do this exactly. Just implement a visitor that visits every instruction and avoids visiting injected instrumentation instructions. Remember how I said I'm refactoring the emitter to pass the instruction that is currently being visited to a bunch of objects that determine if it's an `instr_of_interest`? So it'll no longer be the responsibility of the visitor/emitter to decide that. It'll be the responsibility of those objects (that correspond with the probe rules, e.g. is the current instruction of interest for the used `wasm:bytecode:call` rule?)

**Comment by ahuoguo** [comment]
Closing this branch due to huge refactoring in master

**Pull request closed without merging**
